### PR TITLE
3rd party 1.3.0 release changes

### PR DESCRIPTION
**Pull request by ripienaar**
This is the changes made by @kamenevn mentioned in https://github.com/stretchr/bitbar/issues/8

### CODE REVIEW

**Comment by ripienaar** [comment]
this PR doesn't seem to update the version number though, I don't know OS X coding I am mainly responding to @matryer asking if someone can make a PR.

**Comment by ripienaar** [comment]
Any chance we'll see a update released for this tool? It's really rather nice and unfortunately quite unique

**Comment by kamenevn** [comment]
@ripienaar What update do you want to see?

**Comment by ripienaar** [comment]
@kamenevn I want these changes merged to the main branch and an official release made.

**Comment by kamenevn** [comment]
@ripienaar  https://github.com/stretchr/bitbar/pull/12

**Comment by ripienaar** [comment]
@kamenevn indeed, I made the same PR.  It's up to @matryer to make a release I suppose, that was the question.

**Comment by matryer** [comment]
Would you guys like to be contributors to the project? Then you can make the release - as I am snowed under this week.

**Comment by ripienaar** [comment]
@matryer thanks - personally, I have no idea about OS X coding, so I'd pass - that's a generous offer though.

**Comment by matryer** [comment]
see https://github.com/matryer/bitbar/releases/tag/v1.3.1

**Pull request merged**
